# Generated by Django 4.0.5 on 2022-06-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='watch_count',
            field=models.IntegerField(),
        ),
    ]
